name: Build TS and Deploy

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: npm install esbuild

      - run: npx esbuild j.ts --minify --format=esm --outfile=j.js

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .  # Include j.js, index.html, etc.

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/deploy-pages@v4
