name: Build and Minify

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install esbuild
        run: npm install --global esbuild

      - name: Build and Minify with esbuild
        run: |
          esbuild src/index.ts \
            --bundle \
            --minify \
            --outfile=docs/app.js \
            --format=esm

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
